### ISSUE TITLE
Simulation runtime errors for snappy, LZ4 and casssandra

### ISSUE THREAD

**Issue by infomaven** [Mishail/GatlingCql#2]
Congrats on a great tool idea. I've been using Gatling around 7 months and enjoy it a lot. Now that I've been tasked to test a Cassandra data model, I jumped at the chance to use Gatling for the job. 

I was able to clone this project, assemble a tarball and  unpack it into my local  install of Gatling (whew.... this was my first time doing such a procedure  ). 

 When I started Gatling and selected the Cassandra Simulation, it threw some runtime errors.

These all seem to be DataStax / Cassandra-related dependencies. Do I need to have Cassandra installed locally to use this tool, and if so, what is the recommended installation or version to use? This would be good information to include in the README. 

using 
- Mac OSX 10 Mavericks
- GatlingCql-GatlingCql-0.0.2.tar.gz
- gatling-charts-highcharts-bundle-2.1.4
- Java8, Scala 2.11
- IntelliJ 14

Full stack trace is below. 

Simulation cassandra.CassandraSimulation started...
```
00:18:35.772 [WARN ] c.d.d.c.FrameCompressor - Cannot find Snappy class, you should make sure the Snappy library is in the classpath if you intend to use it. Snappy compression will not be available for the protocol.
00:18:35.775 [WARN ] c.d.d.c.FrameCompressor - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.TransportException: [/127.0.0.1:9042] Cannot connect))```

**Comment by doanduyhai** [comment]
" Do I need to have Cassandra installed locally to use this tool, and if so, what is the recommended installation or version to use?" --> You should have configured properly the `Cluster` object by giving an appropriate IP address pointing to a running Cassandra.

"This would be good information to include in the README." --> it is indeed in the README.

`val session = Cluster.builder().addContactPoint("127.0.0.1")`

**Comment by Mishail** [comment]
@infomaven yes, you should have a Cassandra cluster running somewhere. There are tons of information how to do that, and https://github.com/pcmanus/ccm could be a good start.

And those Snappy/LZ4 messages are not errors, just warnings. Those from the DataStax Java Driver, more info at http://www.datastax.com/documentation/developer/java-driver/2.1/index.html

**Comment by infomaven** [comment]
Thanks for the link on Cassandra setup in GitHub.
I am a total beginner with Cassandra and with Maven, so this has all been a huge learning experience. Thank goodness I have fairly clear understanding of Gatling.
 It looks like the the pom file references older versions of everything I am using on my dev box  (especially Gatling version). What would happen if I updated these to reflect what I actually have installed? <properties>
   <maven.compiler.source>1.7</maven.compiler.source>     ### I have Java 8
   <maven.compiler.target>1.7</maven.compiler.target>
   <encoding>UTF-8</encoding>
   <scala.version>2.10.4</scala.version>                  ### I have Scala 2.11
   <gatling.version>2.0.0-RC5</gatling.version>           ### I have Gatling 2.1.4
</properties>

I also see there is no mechanism in the Gatling code or in the build file to start Cassandra automatically, even though it is a critical dependency for the Simulation. I'd like to adopt this project for a cloud installation of  Cassandra, so I'll be looking into a way to start up Cassandra and tear it down when the script finishes. 
I'm going to think about this and see if I can come up with something to contribute back.

- Nadine

Date: Sat, 7 Mar 2015 10:35:45 -0800
